version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/carlpett/influxdb_stats_exporter
    steps:
      - checkout
      - run: make build
  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/carlpett/influxdb_stats_exporter
    steps:
      - checkout
      - run: echo -n "Building release for "; git describe --always --tags | tee VERSION
      - run: promu crossbuild
      - run: promu crossbuild tarballs
      - run: promu checksum .tarballs
      - run: promu release .tarballs
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
