version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - restore_cache:
          keys:
            - go-cache
      - checkout
      - run:
          name: Set version
          command: echo -n "Building release for "; git describe --always --tags | sed 's/^v//' | tee VERSION
      - run: make build
      - save_cache:
          key: go-cache
          paths:
            - /go/pkg
            - /root/.cache/go-build
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - restore_cache:
          keys:
            - go-cache
      - checkout
      - run:
          name: Set version
          command: echo -n "Building release for "; git describe --always --tags | sed 's/^v//' | tee VERSION
      - run: make crossbuild
      - store_artifacts:
          path: binaries
          destination: releases
      - run: make release

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
