version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go mod tidy
      - run: make build
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go mod tidy
      - run:
          name: Set version
          command: echo -n "Building release for "; git describe --always --tags | sed 's/^v//' | tee VERSION
      - run: make tarball
      - run:
          name: Download github-release tool
          command: curl -sL 'https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2' | tar xjf - --strip-components 3 -C /go/bin
      - run: promu release tarballs
      - run: promu checksum tarballs
      - store_artifacts:
          path: tarballs
          destination: releases

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
